# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: neozt
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: leetcode-daily
# "service" is the name of this project. This will also be added to your AWS resource names.
service: leetcode-daily

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1
  environment:
    BASE_URL: https://leetcode-daily.neozt.dev

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "arn:aws:s3:::leetcode-daily/*"

resources:
  Resources:
    MyS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: leetcode-daily
        VersioningConfiguration:
          Status: Enabled

functions:
  api:
    description: Express.js backend for redirecting to LeetCode's Problem of the Day.
    handler: src/app.handler
    memorySize: 128
    logRetentionInDays: 14
    events:
      - httpApi: "GET /"
      - httpApi: "GET /about"
  #      - httpApi: "GET /ip"

  import-job:
    description: Scheduled job to save Leetcode POTD data into S3.
    handler: src/import-job.handler
    memorySize: 128
    logRetentionInDays: 14
    events:
      - schedule: cron(5 0 * * ? *)
