# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: neozt
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: leetcode-daily
# "service" is the name of this project. This will also be added to your AWS resource names.
service: leetcode-daily

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1
  environment:
    BASE_URL: https://leetcode-daily.neozt.dev/
    GITHUB_URL: https://github.com/neozt/leetcode-daily
    DAILY_QUESTION_TABLE_NAME:
      Ref: DailyQuestion

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [ DailyQuestion, Arn ]

stages:
  default:
    params:
      dailyQuestionTableName: DailyQuestion-${sls:stage}
  prod:
    params:
      dailyQuestionTableName: DailyQuestion

resources:
  Resources:
    DailyQuestion:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${param:dailyQuestionTableName}
        BillingMode: PROVISIONED
        AttributeDefinitions:
          - AttributeName: type
            AttributeType: S
          - AttributeName: date
            AttributeType: S
        KeySchema:
          - AttributeName: type
            KeyType: HASH
          - AttributeName: date
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  api:
    description: Express.js backend for redirecting to LeetCode's Problem of the Day.
    handler: src/functions/app.handler
    memorySize: 128
    logRetentionInDays: 14
    events:
      - httpApi: "GET /"
      - httpApi: "GET /about"
  #      - httpApi: "GET /ip"

  import-job:
    description: Scheduled job to save Leetcode POTD data into S3.
    handler: src/functions/import-job.handler
    memorySize: 128
    logRetentionInDays: 14
    events:
      - schedule: cron(5 0 * * ? *)
